### ISSUE TITLE
2 задание не верное

### ISSUE THREAD

**Issue by tim-teacher** [NatalyaLemeshevskaya/AndroidLesson#1]
AndroidLesson/Lesson2/src/Lesson2.java
1) 
`       for (int i = 1; i < array.length; i++) {
            array[Indmin]=0;
            array[Indmax]=99;
        }
`
Не уверен что этот код работает корректно, почему начинаете с 1 индекса, а не с нулевого? Вы же тут ищите мин и мак, и если он будет на нуле, то вы замените не те данные.
Во вторых зачем делать одно и тоже так много раз? Я про:
`   array[Indmin]=0;
     array[Indmax]=99;`
Это достаточно вызвать только один раз.

2) Задание не работает с данными:
`  float[] array2={6.2f,5.3f,5.3f,8f,8f,4.2f,5.3f,9f,9f,6.2f};`
Выдает:
[6.2] - повторений 2
[5.3] - повторений 3
[5.3] - повторений 2
[8.0] - повторений 2
[9.0] - повторений 2

**Comment by NatalyaLemeshevskaya** [comment]
fixed
